FROM dockerregistry.lnls-sirius.com.br/gas/epics-base:base-3.15-debian-9.13

ENV EPICS_DEV_COMMIT base-3.15-synapps-lnls-R1-2-1

ENV EPICS_BASE /opt/epics/base
ENV EPICS_SUPPORT /opt/epics/synApps/support
ENV EPICS_MODULES /opt/epics/modules


RUN git clone https://github.com/lnls-sirius/epics-dev.git /tmp/epics-dev && \
    cd /tmp/epics-dev && \
    git checkout ${EPICS_DEV_COMMIT} && \
    ./run-all.sh -o -i -c -r yes && \
    cd / && \
    rm -rf /tmp/epics-dev && \
    rm -rf /var/lib/apt/lists/*

# Utility
RUN apt update -y && apt install tree procps -y
RUN set -x; \
    ln --verbose --symbolic $(ls --directory /opt/epics/synApps*) /opt/epics/synApps

# caputlog
ARG CAPUTLOG_VERSION=R3.7
ARG CAPUTLOG_URL=https://github.com/epics-modules/caPutLog/archive/${CAPUTLOG_VERSION}.tar.gz
ENV CAPUTLOG caPutLog-${CAPUTLOG_VERSION}
LABEL br.com.lnls-sirius.caputlog=${CAPUTLOG_URL}
RUN set -xe;\
    cd ${EPICS_SUPPORT};\
    wget -O ${CAPUTLOG}.tar.gz ${CAPUTLOG_URL};\
    tar -zxvf ${CAPUTLOG}.tar.gz;\
    rm -f ${CAPUTLOG}.tar.gz;\
    cd ${CAPUTLOG};\
    sed -i -e 's|^EPICS_BASE=.*$|EPICS_BASE=/opt/epics/base|' configure/RELEASE && \
    make -j$(nproc)

# procServControl
ARG PCTRL_URL=http://controls.diamond.ac.uk/downloads/support/procServControl/1-2/procServControl-1-2.tgz
LABEL br.com.lnls-sirius.procservControl=${PCTRL_URL}
ENV PROCSERVCONTROL ${EPICS_SUPPORT}/procServControl-1-2
RUN set -x;\
    set -e;\
    cd ${EPICS_SUPPORT};\
    wget -O ${PROCSERVCONTROL}.tar.gz ${PCTRL_URL};\
    tar -zxf ${PROCSERVCONTROL}.tar.gz;\
    rm -f ${PROCSERVCONTROL}.tar.gz;\
    cd ${PROCSERVCONTROL};\
    sed -i \
        -e '18s/^/#/' Makefile;\
    sed -i\
       -e 's|^EPICS_BASE=.*$|EPICS_BASE=/opt/epics/base|' \
       -e 's|^SUPPORT=.*$|SUPPORT=/opt/epics/synApps/support|' \
       -e 's|^SNCSEQ=.*$|SNCSEQ=$(SUPPORT)/seq-2-2-6|' \
       -e 's|^ASYN=.*$|ASYN=$(SUPPORT)/asyn-R4-35|' \
       -e 's|^BUSY=.*$|BUSY=$(SUPPORT)/busy-R1-7-1|' \
       configure/RELEASE;\
   make -j$(nproc)

# procCtrl app
COPY procCtrl /opt/epics/procCtrl
ENV PROC_CTRL_APP /opt/epics/procCtrl
ENV PROC_CTRL_APP_BOOT ${PROC_CTRL_APP}/iocBoot/iocprocCtrl
RUN set -xe; \
    cd /opt/epics/procCtrl; \
    sed -i\
       -e 's|^EPICS_BASE=.*$|EPICS_BASE=/opt/epics/base|' \
       -e 's|^SUPPORT=.*$|SUPPORT=/opt/epics/synApps/support|' \
       -e "s|^PROCSERVCONTROL=.*$|PROCSERVCONTROL=${PROCSERVCONTROL}|" \
       -e 's|^SNCSEQ=.*$|SNCSEQ=$(SUPPORT)/seq-2-2-6|' \
       -e 's|^ASYN=.*$|ASYN=$(SUPPORT)/asyn-R4-35|' \
       -e 's|^BUSY=.*$|BUSY=$(SUPPORT)/busy-R1-7-1|' \
       -e "s|^CAPUTLOG=.*$|CAPUTLOG=\$(SUPPORT)/${CAPUTLOG}|" \
       configure/RELEASE; \
   make -j$(nproc)
